# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
#######################################################################################
# Book settings
title                       : ""  # The title of the book. Will be placed in the left navbar.
author                      : 刘早起@<a href="https://pic.liuzaoqi.com/picgo/202112150908823.jpeg" target="_blank"  style=" color:#333;">微信公众号:早起Python</a>｜友情链接 -> <a href="https://iswbm.com/" target="_blank" style=" color:#333;">明哥教程 🚀</a>｜<a href="https://beian.miit.gov.cn/" target="_blank"  style=" color:#333;">皖ICP备2021017583号-1</a>｜<a href="https://pic.liuzaoqi.com/picgo/202112150908823.jpeg" target="_blank"><img src="https://img.shields.io/badge/微信公众号-5w%2B-green?logo=wechat&style=social" style="padding-bottom:0.2em;" /></a> &nbsp; <a href="https://github.com/liuhuanshuo/zaoqi-book" target="_blank"><img src="https://img.shields.io/github/stars/liuhuanshuo/zaoqi-book.svg?logo=Github&style=social" style="padding-bottom:0.2em;" /></a> &nbsp; <a href="https://www.zhihu.com/people/almost-lover-1hs" target="_blank"><img src="https://img.shields.io/badge/%20follow-5k-green?logo=zhihu&style=social&logoColor=#019DFF" style="padding-bottom:0.2em;" /></a> &nbsp; <a href="https://pandas.liuzaoqi.com/doc/chapter10/donate.html"><img src="https://img.shields.io/badge/赞赏-请早起喝咖啡～-green?logo=CoffeeScript&style=social&logoColor=critical" style="padding-bottom:0.2em;" /></a>
copyright                   : "2020-2021"  # Copyright year to be placed in the footer
logo                        : mylogo.png  # A path to the book logo
email                       : "huanshuo0801@gmail.com"
exclude_patterns            : ['README.md']  # Patterns to skip when building the book. Can be glob-style (for example "*skip.ipynb")
only_build_toc_files          : true
#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns:
    - 'doc/chapter1/数据存储.ipynb'
#######################################################################################
#交互式代码
launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (for example, https://mybinder.org)
  thebe                     : true

repository:
  url                       : https://github.com/liuhuanshuo/zaoqi-book  # Online location of your book
  branch                    : main # Which branch of the repository should be used when creating links (optional)
  path_to_book              : ""
#######################################################################################
# HTML-specific settings
html:
  comments:
    hypothesis: false
  favicon                   : "images/logo.png"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages.
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : "UA-214732125-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
#######################################################################################
# Advanced and power-user settings
parse:
  myst_substitutions:
      sub3: My _global_ value!
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
#######################################################################################
sphinx:
  config:
    html_show_copyright: false
#    html_js_files:
#      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd

extra_extensions:
    - sphinx_click.ext
    - sphinx_inline_tabs
    - sphinxext.rediraffe
    - sphinx_proof
    - myst_nb
    - sphinx_thebe
    - html_image